### ISSUE TITLE
Include PDB With Binary Packages

### ISSUE THREAD

**Issue by GrizzledHacker** [ermaccer/MK1Hook#10]
Could you distribute debugging symbols with MK1Hook?

**Comment by ermaccer** [comment]
What for? Do you have a crash somewhere?
Source code is there, you can always compile it yourself to get the PDB.

**Comment by GrizzledHacker** [comment]
My friend is hitting a crash.  I got him to run procdump and have the dump, but I can't manage to get source compiling.  I think you are using a very old Windows SDK

**Comment by ermaccer** [comment]
It's built with VS 2022. Send the .dmp if you can or just reproduction steps. If its something to do with script calling then probably won't be able to help much as they changed a ton with MK12.
