### ISSUE TITLE
Kameo Override Icon & Name

### ISSUE THREAD

**Issue by orn8** [ermaccer/MK1Hook#12]
When you switch your kameo through the mk1hook menu, the icon at the top still shows the one selected in the kameo select menu. Is it possible to update the icon and name to reflect the chosen mk1hook kameo, similar to how NPC characters chosen through the mk1hook display their name regardless of the one chosen in the character select menu?

Thanks in advance.

**Comment by ermaccer** [comment]
If you just restart the match they should appear, keep in mind that most kameo npcs don't have any icons actually assigned so it will be a blank spot and that's not really my fault.

**Comment by orn8** [comment]
All good. I just realised that, so that's why I closed the issue.
